function rankingScore(t){const g=t.w+t.l,wp=g?t.w/g:0,sos=g?t.sos/g:60,margin=g?(t.pf-t.pa)/g:0,p=profiles(t).overall;return wp*60+p*.22+sos*.10+clamp(margin,-20,20)*.4}
function ranked(){let r=[...universe.teams].sort((a,b)=>rankingScore(b)-rankingScore(a));r.forEach((t,i)=>t.rank=i+1);return r}
function findUserGame(){if(universe.phase!=='regular'||universe.week>=12)return null;const n=$('#userTeam').value;return universe.schedule[universe.week].find(g=>!g.played&&(g.home===n||g.away===n))||null}
function simulateUserDetailed(){const g=findUserGame();if(!g)return;recoverWeek();const r=detailedGame(T(g.home),T(g.away),false,g.conf);g.played=true;g.score=[r.ap,r.hp];g.winner=r.winner;g.detailed=true;universe.lastDetailedGame=r;universe.latest=[r];ranked();render()}
function simWeek(){if(universe.phase!=='regular'||universe.week>=12)return;recoverWeek();let results=[];for(const g of universe.schedule[universe.week]){if(g.played)continue;let r=gameSim(T(g.home),T(g.away),false,g.conf);g.played=true;g.score=[r.ap,r.hp];g.winner=r.winner;results.push(r)}universe.week++;if(results.length)universe.latest=results;ranked();advanceRecruiting();if(universe.week===12)universe.phase='confReady';render()}
function simSeason(){while(universe.phase==='regular')simWeek();render()}
function confStand(c){return universe.teams.filter(t=>t.conference===c).sort((a,b)=>b.cw-a.cw||b.w-a.w||rankingScore(b)-rankingScore(a))}
function simConferenceChampionships(){if(universe.phase!=='confReady')return;universe.latest=[];universe.confChamps=[];allConfs().forEach(c=>{let s=confStand(c);if(s.length<2)return;let r=gameSim(s[0],s[1],true,false),w=T(r.winner);w.champ=true;universe.confChamps.push(w);universe.latest.push({...r,label:c+' Championship'})});universe.phase='playoffReady';ranked();render()}
function seedField(){let r=ranked(),set=new Set(universe.confChamps.map(t=>t.name)),ats=r.filter(t=>!set.has(t.name)).slice(0,6);return [...universe.confChamps,...ats].sort((a,b)=>rankingScore(b)-rankingScore(a)).slice(0,16)}
function simPlayoff(){if(universe.phase!=='playoffReady')return;let field=seedField();field.forEach((t,i)=>t.seed=i+1);let logs=[];function round(arr,label){let out=[];for(let i=0;i<arr.length/2;i++){let a=arr[i],b=arr[arr.length-1-i],r=gameSim(a,b,true,false);logs.push({...r,label});out.push(T(r.winner))}return out}let r16=round(field,'Round of 16'),q=round(r16,'Quarterfinal'),s=round(q,'Semifinal'),f=round(s,'National Championship');universe.champion=f[0].name;universe.phase='complete';universe.latest=logs;archiveSeason();ranked();render()}
function archiveSeason(){if(universe.history.some(h=>h.year===universe.year&&h.type==='season'))return;universe.history.unshift({type:'season',year:universe.year,champion:universe.champion,top10:ranked().slice(0,10).map(t=>({name:t.name,record:`${t.w}-${t.l}`})),records:universe.teams.map(t=>({name:t.name,w:t.w,l:t.l,cw:t.cw,cl:t.cl,pf:t.pf,pa:t.pa,prestige:t.prestige})),userTeam:$('#userTeam').value})}
function recruitPitch(t,r){let v=t.prestige*.32+t.nil*.16+t.development*.15+t.academics*.06+t.facilities*.07+t.staff.RC.recruiting*.10+t.staff.HC.recruiting*.05+(t.w-t.l)*.7;v+=pipelineStrength(t,r.homeRegion)*.10;if(t.conference===r.homeRegion)v+=3;switch(r.priority){case'Prestige':v+=t.prestige*.18;break;case'NIL':v+=t.nil*.20;break;case'Development':v+=t.development*.18;break;case'Early Role':v+=Math.max(0,90-unit(t,[r.pos]))*.20;break;case'Coaching':v+=(t.staff.HC.loyalty+t.staff.RC.recruiting)*.08;break;case'Academics':v+=t.academics*.18;break;case'Scheme Fit':v+=t.offScheme==='Multiple'?8:5;break;case'Winning':v+=(t.w/(Math.max(1,t.w+t.l)))*18;break}return v}
function scheduleVisit(r){const u=selected();if(r.visitWeek){r.visitWeek=null;r.visit=false;return}let g=u.schedule.find(g=>!g.played&&g.home===u.name&&g.week>=universe.week+1);r.visitWeek=g?g.week:Math.min(12,universe.week+1);r.visit=true}
function advanceRecruiting(){const u=selected();universe.recruits.forEach(r=>{if(r.committed)return;let pool=universe.teams.slice().sort(()=>Math.random()-.5).slice(0,12).sort((a,b)=>recruitPitch(b,r)-recruitPitch(a,r)),top=pool[0];r.leader=top.name;let promiseBoost=r.promise&&r.promise!=='None'?(r.priority===r.promise?8:4):0,visitBoost=0;if(r.visitWeek===universe.week){let g=u.schedule.find(g=>g.week===universe.week&&g.home===u.name);visitBoost=g&&g.played?(g.winner===u.name?12:6):7;r.visit=false}let us=recruitPitch(u,r)+(r.targeted?10:0)+r.relationship*.12+visitBoost+promiseBoost,ais=recruitPitch(top,r);if(r.targeted){r.relationship=clamp(r.relationship+gi(2,6),0,100);r.interest=clamp(Math.round(r.interest+(us-ais)*.07+gi(1,5)+gauss()*2),1,100)}else r.interest=clamp(Math.round(r.interest+(us-ais)*.02+gauss()*2),1,100);if(universe.week>=6&&Math.random()<.035+universe.week*.009){if(r.targeted&&r.interest>=72&&us>=ais-4){r.committed=u.name;u.commits.push(r)}else r.committed=top.name}})}
function autoTarget(){const u=selected();universe.recruits.forEach(r=>r.targeted=false);let needs={};POS.forEach(p=>needs[p]=(POS_COUNTS[p]||4)-u.roster.filter(x=>x.pos===p&&x.year!=='SR').length*.55);universe.recruits.filter(r=>!r.committed).sort((a,b)=>(b.scoutUp+(needs[b.pos]||0)*5)-(a.scoutUp+(needs[a.pos]||0)*5)).slice(0,20).forEach(r=>r.targeted=true);renderRecruiting()}
function carousel(){let log=[];universe.teams.forEach(t=>{Object.values(t.staff).forEach(c=>{c.years++;c.contractYears=Math.max(0,(c.contractYears??2)-1)});let expected=clamp(Math.round((t.prestige-30)/8),4,10),bad=t.w<expected-2,fire=bad&&Math.random()>(t.admin_patience/100);if(fire){let old=t.staff.HC;t.staff.HC=generateCoach('Head Coach',t);log.push(`${t.name} fired ${old.name} after ${t.w}-${t.l}; hired ${t.staff.HC.name}.`)}if(Math.random()<.07+t.staff.OC.ambition/900){let old=t.staff.OC;t.staff.OC=generateCoach('Offensive Coordinator',t);log.push(`${t.name} lost OC ${old.name}; ${t.staff.OC.name} takes over.`)}if(Math.random()<.06+t.staff.DC.ambition/1000){let old=t.staff.DC;t.staff.DC=generateCoach('Defensive Coordinator',t);log.push(`${t.name} changed DC from ${old.name} to ${t.staff.DC.name}.`)}});return log}
function runOffseason(){if(universe.phase!=='complete'||universe.offseasonDone)return;archiveSeason();let move=[],portal=[];const controlled=$('#userTeam').value;universe.teams.forEach(t=>{let prevW=t.w;for(const p of t.roster)archivePlayerSeason(p,t,universe.year);const grads=t.roster.filter(p=>p.year==='SR');for(const p of grads)addToArchive(p,t,'Graduated');t.roster=t.roster.filter(p=>p.year!=='SR');let keep=[];for(const p of t.roster){let risk=transferRisk(p);if(Math.random()<risk/360)portal.push({p,from:t.name});else keep.push(p)}t.roster=keep;t.roster.forEach(p=>{let staffDev=OFF_POS.has(p.pos)?t.staff.OC.development:t.staff.DC.development,old=p.perceived;let delta=Math.round((p.dev*.22+p.work*.18+p.coach*.08+t.development*.16+t.facilities*.10+t.staff.SC.development*.10+staffDev*.08-48)/24+gauss()*2.3);p.trueNow=clamp(p.trueNow+delta,35,99);p.perceived=clamp(Math.round(p.trueNow+gauss()*4),35,99);p.morale=clamp(p.morale+gi(-5,9)-promisePenalty(p)*.15,15,99);p.promiseBaseline??=old;p.year=p.year==='FR'?'SO':p.year==='SO'?'JR':p.year==='JR'?'SR':p.year;p.stats=newStats()});let signed=universe.recruits.filter(r=>r.committed===t.name).slice(0,30);signed.forEach(r=>{let p=generatePlayer(t,r.pos,99);Object.assign(p,{name:r.name,style:r.style,trueNow:r.trueNow,upside:r.upside,perceived:r.scout,perceivedUpside:r.scoutUp,year:'FR',origin:`${r.stars}-star recruit from ${r.homeRegion}`,promise:r.promise&&r.promise!=='None'?r.promise:null,promiseBaseline:r.scout});t.roster.push(p);t.pipelines[r.homeRegion]=clamp(pipelineStrength(t,r.homeRegion)+gi(1,3),0,100)});for(const c of Object.keys(t.pipelines))if(!signed.some(r=>r.homeRegion===c))t.pipelines[c]=clamp(t.pipelines[c]-1,5,100);let target=(t.prestige-50)/9,deltaPrestige=clamp(Math.round((prevW-6-target)*.35),-3,3);t.prestige=clamp(t.prestige+deltaPrestige,10,t.program_ceiling);t.commits=[];if(t.name===controlled)move.push(`${grads.length} seniors graduated; ${signed.length} signees joined; ${deltaPrestige>=0?'+':''}${deltaPrestige} prestige.`)});
 portal.forEach(x=>{let candidates=universe.teams.filter(t=>t.name!==x.from).map(t=>({t,score:t.prestige*.45+t.development*.22+Math.max(0,88-unit(t,[x.p.pos]))*.30+pipelineStrength(t,T(x.from)?.conference||t.conference)*.05+gauss()*6})).sort((a,b)=>b.score-a.score),dest=candidates[0].t;x.p.origin=`Transfer from ${x.from}`;x.p.morale=clamp(70+gi(-5,12),30,95);x.p.promise=null;dest.roster.push(x.p);if(x.from===controlled||dest.name===controlled)move.push(`${x.p.pos} ${x.p.name}: ${x.from} → ${dest.name}`)});
 move.push(...carousel().filter(x=>x.includes(controlled)));universe.movementLog=move.slice(0,100);universe.year++;universe.week=0;universe.recoveredWeek=-1;universe.phase='regular';universe.latest=[];universe.confChamps=[];universe.champion=null;universe.lastDetailedGame=null;universe.recruits=generateRecruitPool(900);universe.teams.forEach(t=>{t.w=t.l=t.cw=t.cl=t.pf=t.pa=t.sos=0;t.rank=null;t.champ=false;while(t.roster.length<85)t.roster.push(generatePlayer(t,pick(POS),99));if(t.roster.length>105){let keep=t.roster.sort((a,b)=>b.trueNow-a.trueNow).slice(0,105),cut=t.roster.filter(p=>!keep.includes(p));for(const p of cut)addToArchive(p,t,'Roster cut');t.roster=keep}autoDepthTeam(t,false)});universe.offseasonDone=false;buildSchedule();ranked();render()}
function transferRisk(p){return clamp((58-p.morale)+(p.role==='Development'?12:0)+(p.role==='Redshirt candidate'?8:0)+promisePenalty(p)+(p.injuryWeeks>3?3:0),0,100)}
function playerGrade(p){return grade(p.perceived)}
function upsideLabel(p){let g=p.perceivedUpside-p.perceived;return g>=18?'Huge':g>=11?'High':g>=6?'Moderate':'Limited'}
