function normalizeUniverse(){universe.version='0.5';universe.movementLog??=[];universe.lastDetailedGame??=null;universe.playerArchive??=[];universe.recoveredWeek??=-1;universe.teams.forEach(t=>{t.staff??=generateStaff(t);for(const c of Object.values(t.staff)){c.contractYears??=gi(1,4);c.salary??=1.2}t.offScheme??=pick(Object.keys(OFF_SCHEMES));t.defScheme??=pick(Object.keys(DEF_SCHEMES));t.nickname??='';t.commits??=[];t.pipelines??=makePipelines(t);t.roster.forEach(p=>{p.speed??=clamp(p.trueNow+gi(-8,8),25,99);p.power??=clamp(p.trueNow+gi(-8,8),25,99);p.technique??=clamp(p.trueNow+gi(-8,8),25,99);p.iq??=clamp(p.trueNow+gi(-10,10),20,99);p.composure??=65;p.durability??=70;p.versatility??=60;p.health??=100;p.wear??=0;p.injury??=null;p.injuryWeeks??=0;p.injuryHistory??=[];p.seasonHistory??=[];p.promise??=null;p.promiseBaseline??=p.perceived;p.stats??=newStats();p.career??={games:0,passYds:0,passTD:0,int:0,rushYds:0,rushTD:0,recYds:0,recTD:0}});ensureDepth(t)});universe.recruits.forEach(r=>{r.homeRegion??=pick(allConfs());r.priority??=pick(PRIORITIES);r.relationship??=0;r.visit??=false;r.visitWeek??=null;r.promise??='None'})}
function setStatus(x){$('#saveStatus').textContent=x}
function openDB(){return new Promise((res,rej)=>{let q=indexedDB.open('DynastyLabDB',1);q.onupgradeneeded=()=>q.result.createObjectStore('saves');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function saveBrowser(){try{let db=await openDB(),tx=db.transaction('saves','readwrite');tx.objectStore('saves').put({universe,userTeam:$('#userTeam').value,savedAt:new Date().toISOString()},'main');await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error)});setStatus(`Saved ${universe.year}, Week ${universe.week} to browser storage.`)}catch(e){setStatus('Browser save failed. Use Export Save instead.')}}
async function loadBrowser(){try{let db=await openDB(),tx=db.transaction('saves','readonly'),req=tx.objectStore('saves').get('main');let d=await new Promise((r,j)=>{req.onsuccess=()=>r(req.result);req.onerror=()=>j(req.error)});if(!d){setStatus('No browser save found.');return}universe=d.universe;normalizeUniverse();refreshTeamOptions(d.userTeam);render();setStatus(`Loaded browser save from ${d.savedAt||'earlier session'}.`)}catch(e){setStatus('Browser load failed. Use Import Save if you exported one.')}}
function exportSave(){let blob=new Blob([JSON.stringify({version:'0.5',userTeam:$('#userTeam').value,universe})],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dynasty-lab-${universe.year}-week-${universe.week}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setStatus('Save exported as JSON.')}
function importSave(file){let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);universe=d.universe||d;normalizeUniverse();refreshTeamOptions(d.userTeam||universe.teams[0].name);render();setStatus('Imported save file successfully.')}catch(e){setStatus('Import failed: invalid save file.')}};r.readAsText(file)}
function refreshTeamOptions(sel){$('#userTeam').innerHTML='';universe.teams.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(s=>{let o=document.createElement('option');o.value=s.name;o.textContent=s.name;$('#userTeam').appendChild(o)});$('#userTeam').value=T(sel)?sel:universe.teams[0].name}
function bind(){
 $$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
 $('#simWeek').onclick=simWeek;$('#seasonWeek').onclick=simWeek;$('#simSeason').onclick=simSeason;$('#simConf').onclick=simConferenceChampionships;$('#simPlayoff').onclick=simPlayoff;$('#simDetailedGame').onclick=simulateUserDetailed;$('#autoTarget').onclick=autoTarget;$('#autoDepth').onclick=()=>{autoDepthTeam(selected(),true);render()};$('#archiveSearch').oninput=renderArchiveSearch;$('#runOffseason').onclick=runOffseason;$('#positionFilter').onchange=renderRoster;$('#userTeam').onchange=render;$('#applyProgramEdit').onclick=applyProgramEdit;
 $('#saveBrowser').onclick=saveBrowser;$('#loadBrowser').onclick=loadBrowser;$('#exportSave').onclick=exportSave;$('#importSave').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{if(e.target.files[0])importSave(e.target.files[0])};
 $('#newUniverse').onclick=()=>{if(confirm('Generate a completely new universe? Unsaved progress will be lost.')){initUniverse();refreshTeamOptions('Chicago Metropolitan');render();setStatus('New universe generated.')}};
}
loadSchools().then(()=>{initUniverse();refreshTeamOptions('Chicago Metropolitan');POS.forEach(p=>{let o=document.createElement('option');o.value=p;o.textContent=p;$('#positionFilter').appendChild(o)});allConfs().forEach(c=>{let o=document.createElement('option');o.value=c;o.textContent=c;$('#editConference').appendChild(o)});bind();render();setStatus('v0.5 ready. Export or Save to preserve a dynasty.');}).catch(e=>{$('#app').innerHTML='<div style="padding:30px">Could not initialize Dynasty Lab. '+e.message+'</div>'});
