function T(name){return universe.teams.find(t=>t.name===name)}
function selected(){return T($('#userTeam').value)}
function allConfs(){return [...new Set(universe.teams.map(t=>t.conference))]}
function starter(team,pos){return team.roster.filter(p=>p.pos===pos).sort((a,b)=>b.trueNow-a.trueNow)[0]||team.roster[0]}
function unit(team,positions){let v=[];positions.forEach(p=>{const a=team.roster.filter(x=>x.pos===p).sort((x,y)=>y.trueNow-x.trueNow);const n=(p==='WR'||p==='CB')?3:['OT','OG','EDGE','DT','LB','S'].includes(p)?2:1;v.push(...a.slice(0,n).map(x=>x.trueNow))});return avg(v)}
function playerSchemeFit(p,t){const scheme=OFF_POS.has(p.pos)?OFF_SCHEMES[t.offScheme]:DEF_SCHEMES[t.defScheme], vals=scheme.traits.map(k=>p[k]||p.trueNow);let fit=avg(vals);if(p.pos==='QB'&&scheme.qb&&scheme.qb.includes(p.style))fit+=8;return clamp(Math.round(fit),35,99)}
function profiles(t){
 const qb=unit(t,['QB']),skill=unit(t,['RB','WR','TE']),ol=unit(t,['OT','OG','C']),front=unit(t,['EDGE','DT','LB']),coverage=unit(t,['CB','S']);
 const offPlayers=t.roster.filter(p=>OFF_POS.has(p.pos)).sort((a,b)=>b.trueNow-a.trueNow).slice(0,22),defPlayers=t.roster.filter(p=>!OFF_POS.has(p.pos)).sort((a,b)=>b.trueNow-a.trueNow).slice(0,22);
 const offFit=avg(offPlayers.map(p=>playerSchemeFit(p,t))),defFit=avg(defPlayers.map(p=>playerSchemeFit(p,t))),oc=t.staff.OC,dc=t.staff.DC;
 const offense=clamp(qb*.29+skill*.27+ol*.22+offFit*.08+oc.playCall*.07+oc.development*.03+t.facilities*.04,35,99),defense=clamp(front*.39+coverage*.32+defFit*.09+dc.playCall*.08+dc.development*.04+t.facilities*.04+DEF_SCHEMES[t.defScheme].run*.02+DEF_SCHEMES[t.defScheme].coverage*.02,35,99);
 return {qb,skill,ol,front,coverage,offFit,defFit,offense,defense,overall:(offense+defense)/2};
}
function circlePair(arr,round){let a=[...arr],fixed=a[0],rest=a.slice(1);for(let r=0;r<round;r++)rest=[rest.at(-1),...rest.slice(0,-1)];a=[fixed,...rest];let o=[];for(let i=0;i<a.length/2;i++)o.push([a[i],a[a.length-1-i]]);return o}
function buildSchedule(){universe.teams.forEach(t=>t.schedule=[]);universe.schedule=Array.from({length:12},()=>[]);const cn=allConfs();for(let w=0;w<4;w++)circlePair(cn,w).forEach(([ca,cb])=>{const A=universe.teams.filter(t=>t.conference===ca),B=universe.teams.filter(t=>t.conference===cb);for(let i=0;i<Math.min(A.length,B.length);i++){let j=(i+w)%B.length,home=(i+w)%2===0?A[i]:B[j],away=home===A[i]?B[j]:A[i];universe.schedule[w].push({week:w+1,home:home.name,away:away.name,conf:false,played:false})}});allConfs().forEach(c=>{let arr=universe.teams.filter(t=>t.conference===c);if(arr.length%2)return;for(let r=0;r<8;r++)circlePair(arr,r).forEach(([a,b],k)=>{let home=(r+k)%2===0?a:b,away=home===a?b:a;universe.schedule[4+r].push({week:r+5,home:home.name,away:away.name,conf:true,played:false})})});universe.schedule.flat().forEach(g=>{T(g.home)?.schedule.push(g);T(g.away)?.schedule.push(g)})}
function recordGame(home,away,hp,ap,conf){const H=profiles(home),A=profiles(away),win=hp>ap?home:away,lose=win===home?away:home;win.w++;lose.l++;if(conf){win.cw++;lose.cl++}home.pf+=hp;home.pa+=ap;away.pf+=ap;away.pa+=hp;home.sos+=A.overall;away.sos+=H.overall;return win}
function applyStarterStats(team,s){const qb=starter(team,'QB'),rb=starter(team,'RB'),wr=starter(team,'WR');qb.stats.games++;qb.stats.passYds+=s.passYds;qb.stats.passTD+=s.passTD;qb.stats.int+=s.int;rb.stats.games++;rb.stats.rushYds+=s.rushYds;rb.stats.rushTD+=s.rushTD;wr.stats.games++;wr.stats.recYds+=s.recYds;wr.stats.recTD+=s.recTD}
function gameSim(home,away,neutral=false,confOverride=null){
 const H=profiles(home),A=profiles(away),ha=neutral?0:2.2,schemeH=OFF_SCHEMES[home.offScheme],schemeA=OFF_SCHEMES[away.offScheme];
 function side(O,D,team,scheme,n){let pts=0,passYds=0,passTD=0,int=0,rushYds=0,rushTD=0,recYds=0,recTD=0;for(let i=0;i<n;i++){let edge=(O.offense-D.defense)/11+gauss()*1.15,turn=clamp(.09+(D.coverage-O.qb)*.0015,0.045,.17);if(Math.random()<turn){int+=Math.random()<.72?1:0;continue}let scoreRoll=Math.random()+edge*.075;if(scoreRoll>.80){pts+=7;if(Math.random()<scheme.pass){passTD++;recTD++;let y=gi(24,68);passYds+=y;recYds+=y}else{rushTD++;rushYds+=gi(15,50)}}else if(scoreRoll>.64)pts+=3;passYds+=Math.max(0,Math.round(16+O.qb*.20+O.skill*.09+gauss()*23))*scheme.pass;rushYds+=Math.max(0,Math.round(10+O.skill*.10+O.ol*.07-D.front*.055+gauss()*11))*(1-scheme.pass+.35)}return {pts:Math.round(pts),passYds:Math.round(passYds),passTD,int,rushYds:Math.round(rushYds),rushTD,recYds:Math.round(recYds),recTD}}
 const hs=side(H,A,home,schemeH,gi(10,14)),as=side(A,H,away,schemeA,gi(10,14));let hp=Math.round(hs.pts+ha),ap=as.pts;if(hp===ap)(Math.random()<.5?()=>hp+=3:()=>ap+=3)();const conf=confOverride??home.conference===away.conference;const win=recordGame(home,away,hp,ap,conf);applyStarterStats(home,hs);applyStarterStats(away,as);return {home:home.name,away:away.name,hp,ap,winner:win.name,box:{home:hs,away:as}};
}
function detailedGame(home,away,neutral=false,confOverride=null){
 const H=profiles(home),A=profiles(away),hScheme=OFF_SCHEMES[home.offScheme],aScheme=OFF_SCHEMES[away.offScheme],log=[];
 const totals={home:{plays:0,first:0,passYds:0,passTD:0,int:0,rushYds:0,rushTD:0,recYds:0,recTD:0,sacks:0,turnovers:0},away:{plays:0,first:0,passYds:0,passTD:0,int:0,rushYds:0,rushTD:0,recYds:0,recTD:0,sacks:0,turnovers:0}};
 function drive(off,def,O,D,scheme,out,label){let pos=25,down=1,toGo=10,plays=0;const qb=starter(off,'QB'),rb=starter(off,'RB'),wr=starter(off,'WR'),oc=off.staff.OC,dc=def.staff.DC;while(plays<16){plays++;out.plays++;let pass=scheme.pass+(down===3?.18:0)+(toGo>=8?.09:0)-(toGo<=2?.13:0),pen=Math.random()<.045;if(pen){if(Math.random()<.65){pos=Math.max(1,pos-5);toGo+=5;log.push(`${label}: ${off.name} false start; backed up five.`)}else{pos=Math.min(99,pos+5);toGo=Math.max(1,toGo-5);log.push(`${label}: defensive penalty gives ${off.name} five.`)}continue}
 if(Math.random()<pass){const pressure=clamp(.17+(D.front-O.ol)*.005+(DEF_SCHEMES[def.defScheme].pressure-70)*.0015+(dc.playCall-70)*.001-(oc.playCall-70)*.0008,.08,.48);if(Math.random()<pressure*.28){let loss=gi(3,10);pos=Math.max(1,pos-loss);out.sacks++;down++;toGo+=loss;log.push(`${label}: ${qb.name} sacked for ${loss}.`)}else{let intP=clamp(.027+(D.coverage-O.qb)*.0014+(75-qb.iq)*.0007+(pressure>.30?.009:0),.008,.09);if(Math.random()<intP){out.int++;out.turnovers++;log.push(`${label}: ${qb.name} intercepted near the ${Math.min(99,pos+gi(5,22))}.`);return {points:0,result:'INT',plays}}let comp=clamp(.61+(O.qb-D.coverage)*.004+(qb.technique-70)*.0015-(pressure>.28?.07:0),.38,.79);if(Math.random()<comp){let y=Math.round(clamp(7+(O.skill-D.coverage)/8+gauss()*6,0,38));if(Math.random()<.055+(qb.speed+wr.speed-140)*.0005)y+=gi(12,38);pos+=y;out.passYds+=y;out.recYds+=y;if(y>=toGo){out.first++;down=1;toGo=Math.min(10,100-pos)}else{down++;toGo-=y}log.push(`${label}: ${qb.name} to ${wr.name} for ${y}.`)}else{down++;log.push(`${label}: ${qb.name} incomplete for ${wr.name}.`)}}}
 else{let runEdge=(O.ol*.38+O.skill*.25+rb.power*.15+rb.speed*.12+oc.playCall*.10)-(D.front*.60+DEF_SCHEMES[def.defScheme].run*.20+dc.playCall*.20);let y=Math.round(clamp(3.7+runEdge/20+gauss()*3.2,-4,24));if(Math.random()<.045+Math.max(0,rb.speed-82)*.001)y+=gi(10,32);pos+=y;out.rushYds+=y;if(y>=toGo){out.first++;down=1;toGo=Math.min(10,100-pos)}else{down++;toGo=Math.max(1,toGo-y)}log.push(`${label}: ${rb.name} runs for ${y}.`)}
 if(pos>=100){if(Math.random()<pass){out.passTD++;out.recTD++}else out.rushTD++;log.push(`${label}: TOUCHDOWN ${off.name}.`);return {points:7,result:'TD',plays}}
 if(down>=4){if(pos>=62){let dist=117-pos,pct=clamp(.93-(dist-30)*.011+(starter(off,'K').trueNow-75)*.003,.25,.97);if(Math.random()<pct){log.push(`${label}: ${off.name} field goal good from ${Math.round(dist)}.`);return {points:3,result:'FG',plays}}log.push(`${label}: ${off.name} misses the field goal.`);return {points:0,result:'MISS',plays}}log.push(`${label}: ${off.name} punts.`);return {points:0,result:'PUNT',plays}}
 }return {points:0,result:'END',plays}}
 let hp=0,ap=0;for(let i=1;i<=12;i++){let h=drive(home,away,H,A,hScheme,totals.home,`H${i}`);hp+=h.points;let a=drive(away,home,A,H,aScheme,totals.away,`A${i}`);ap+=a.points}if(!neutral)hp+=Math.random()<.55?3:0;if(hp===ap){log.push('Overtime required.');if(Math.random()<.5)hp+=3;else ap+=3}const conf=confOverride??home.conference===away.conference,win=recordGame(home,away,hp,ap,conf);applyStarterStats(home,totals.home);applyStarterStats(away,totals.away);return {home:home.name,away:away.name,hp,ap,winner:win.name,log:log.slice(-160),box:totals,detailed:true};
}
function rankingScore(t){const g=t.w+t.l,wp=g?t.w/g:0,sos=g?t.sos/g:60,margin=g?(t.pf-t.pa)/g:0,p=profiles(t).overall;return wp*60+p*.22+sos*.10+clamp(margin,-20,20)*.4}
function ranked(){let r=[...universe.teams].sort((a,b)=>rankingScore(b)-rankingScore(a));r.forEach((t,i)=>t.rank=i+1);return r}
function findUserGame(){if(universe.phase!=='regular'||universe.week>=12)return null;const n=$('#userTeam').value;return universe.schedule[universe.week].find(g=>!g.played&&(g.home===n||g.away===n))||null}
function simulateUserDetailed(){const g=findUserGame();if(!g)return;const r=detailedGame(T(g.home),T(g.away),false,g.conf);g.played=true;g.score=[r.ap,r.hp];g.winner=r.winner;g.detailed=true;universe.lastDetailedGame=r;universe.latest=[r];ranked();render()}
function simWeek(){if(universe.phase!=='regular'||universe.week>=12)return;let results=[];for(const g of universe.schedule[universe.week]){if(g.played)continue;let r=gameSim(T(g.home),T(g.away),false,g.conf);g.played=true;g.score=[r.ap,r.hp];g.winner=r.winner;results.push(r)}universe.week++;if(results.length)universe.latest=results;ranked();advanceRecruiting();if(universe.week===12)universe.phase='confReady';render()}
function simSeason(){while(universe.phase==='regular')simWeek();render()}
function confStand(c){return universe.teams.filter(t=>t.conference===c).sort((a,b)=>b.cw-a.cw||b.w-a.w||rankingScore(b)-rankingScore(a))}
