function renderRecruiting(){const u=selected();$('#classSummary').innerHTML=`<strong>${u.commits.length} commitments</strong> · ${universe.recruits.filter(r=>r.targeted&&!r.committed).length} active targets · ${universe.recruits.filter(r=>r.committed===u.name&&r.stars>=4).length} blue chips`;$('#recruitBody').innerHTML=universe.recruits.slice(0,180).map(r=>`<tr class="${r.targeted?'target':''}"><td><strong>${r.name}</strong></td><td>${r.pos}</td><td>${'★'.repeat(r.stars)}</td><td>${r.homeRegion}</td><td>${r.priority}</td><td>${r.style}</td><td>${grade(r.scout)} (${r.scout})</td><td>${grade(r.scoutUp)}</td><td>${r.committed?(r.committed===u.name?'COMMITTED':'Closed'):r.interest+'%'}</td><td>${r.leader||'—'}</td><td>${r.committed?'—':`<button data-visit="${r.id}">${r.visit?'Set':'Visit'}</button>`}</td><td>${r.committed?'':`<button data-target="${r.id}">${r.targeted?'Remove':'Target'}</button>`}</td></tr>`).join('');$$('[data-target]').forEach(b=>b.onclick=()=>{let r=universe.recruits.find(x=>x.id===b.dataset.target);r.targeted=!r.targeted;renderRecruiting()});$$('[data-visit]').forEach(b=>b.onclick=()=>{let r=universe.recruits.find(x=>x.id===b.dataset.visit);r.visit=!r.visit;renderRecruiting()})}
function renderProgram(){const u=selected();$('#editName').value=u.name;$('#editConference').value=u.conference;$('#editPrestige').value=u.prestige;$('#editResources').value=u.resources;$('#editNil').value=u.nil;$('#editDevelopment').value=u.development;$('#editFacilities').value=u.facilities;$('#editAcademics').value=u.academics;$('#programDNA').innerHTML=[['Prestige',u.prestige],['Resources',u.resources],['NIL',u.nil],['Development',u.development],['Facilities',u.facilities],['Academics',u.academics],['Fan Support',u.fan_support],['Admin Patience',u.admin_patience],['Program Ceiling',u.program_ceiling]].map(x=>`<div class="lineitem"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function applyProgramEdit(){const u=selected(),old=u.name,newName=$('#editName').value.trim()||old;if(newName!==old&&T(newName)){alert('A program already uses that name.');return}u.name=newName;for(const [id,key] of [['editPrestige','prestige'],['editResources','resources'],['editNil','nil'],['editDevelopment','development'],['editFacilities','facilities'],['editAcademics','academics']])u[key]=clamp(parseInt($('#'+id).value||u[key],10),1,100);if(newName!==old){universe.schedule.flat().forEach(g=>{if(g.home===old)g.home=newName;if(g.away===old)g.away=newName});universe.teams.forEach(t=>t.schedule.forEach(g=>{if(g.home===old)g.home=newName;if(g.away===old)g.away=newName}));universe.recruits.forEach(r=>{if(r.leader===old)r.leader=newName;if(r.committed===old)r.committed=newName});let opt=[...$('#userTeam').options].find(o=>o.value===old);if(opt){opt.value=newName;opt.textContent=newName}$('#userTeam').value=newName}ranked();render();setStatus('Program changes applied. Conference schedule will fully rebalance next season.')}
function renderOffseason(){const u=selected(),risks=u.roster.map(p=>({p,risk:transferRisk(p)})).sort((a,b)=>b.risk-a.risk).slice(0,8);$('#transferWatch').innerHTML=risks.map(x=>`<div class="lineitem"><span>${x.p.pos} ${x.p.name}</span><span class="${x.risk>45?'bad':x.risk>25?'warn':''}">${Math.round(x.risk)} risk</span></div>`).join('');const dev=u.roster.slice().sort((a,b)=>(b.dev+b.work)-(a.dev+a.work)).slice(0,8);$('#developmentWatch').innerHTML=dev.map(p=>`<div class="lineitem"><span>${p.pos} ${p.name}</span><span>${p.year} · ${p.style}</span></div>`).join('');$('#offseasonReport').textContent=universe.phase==='complete'?`Season complete. Advance to ${universe.year+1} when ready.`:'Complete the season first.';$('#movementLog').innerHTML=universe.movementLog.length?universe.movementLog.map(x=>`<div class="lineitem"><span>${x}</span></div>`).join(''):'<span class="muted">No offseason movement yet.</span>'}
function renderHistory(){let items=[];for(const h of universe.history){if(h.type==='season'){items.push(`<div class="card"><div class="historyrow champ"><span>${h.year} National Champion</span><strong>${h.champion}</strong></div>${h.top10.slice(0,5).map((t,i)=>`<div class="historyrow"><span>#${i+1} ${t.name}</span><span>${t.record}</span></div>`).join('')}</div>`)}else items.push(`<div class="historyrow"><span>${h.year} ${h.event||''}</span><span>${h.detail||''}</span></div>`)}$('#historyLog').innerHTML=items.join('')||'<div class="card muted">No completed seasons yet.</div>'}
function normalizeUniverse(){if(!universe.version)universe.version='0.4';universe.movementLog??=[];universe.lastDetailedGame??=null;universe.teams.forEach(t=>{t.staff??=generateStaff(t);t.offScheme??=pick(Object.keys(OFF_SCHEMES));t.defScheme??=pick(Object.keys(DEF_SCHEMES));t.nickname??='';t.commits??=[];t.roster.forEach(p=>{p.speed??=clamp(p.trueNow+gi(-8,8),25,99);p.power??=clamp(p.trueNow+gi(-8,8),25,99);p.technique??=clamp(p.trueNow+gi(-8,8),25,99);p.iq??=clamp(p.trueNow+gi(-10,10),20,99);p.composure??=65;p.durability??=70;p.versatility??=60;p.stats??=newStats();p.career??={games:0}})});universe.recruits.forEach(r=>{r.homeRegion??=pick(allConfs());r.priority??=pick(PRIORITIES);r.relationship??=0;r.visit??=false})}
function setStatus(x){$('#saveStatus').textContent=x}
function openDB(){return new Promise((res,rej)=>{let q=indexedDB.open('DynastyLabDB',1);q.onupgradeneeded=()=>q.result.createObjectStore('saves');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function saveBrowser(){try{let db=await openDB(),tx=db.transaction('saves','readwrite');tx.objectStore('saves').put({universe,userTeam:$('#userTeam').value,savedAt:new Date().toISOString()},'main');await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error)});setStatus(`Saved ${universe.year}, Week ${universe.week} to browser storage.`)}catch(e){setStatus('Browser save failed. Use Export Save instead.')}}
async function loadBrowser(){try{let db=await openDB(),tx=db.transaction('saves','readonly'),req=tx.objectStore('saves').get('main');let d=await new Promise((r,j)=>{req.onsuccess=()=>r(req.result);req.onerror=()=>j(req.error)});if(!d){setStatus('No browser save found.');return}universe=d.universe;normalizeUniverse();refreshTeamOptions(d.userTeam);render();setStatus(`Loaded browser save from ${d.savedAt||'earlier session'}.`)}catch(e){setStatus('Browser load failed. Use Import Save if you exported one.')}}
function exportSave(){let blob=new Blob([JSON.stringify({version:'0.4',userTeam:$('#userTeam').value,universe})],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dynasty-lab-${universe.year}-week-${universe.week}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setStatus('Save exported as JSON.')}
function importSave(file){let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);universe=d.universe||d;normalizeUniverse();refreshTeamOptions(d.userTeam||universe.teams[0].name);render();setStatus('Imported save file successfully.')}catch(e){setStatus('Import failed: invalid save file.')}};r.readAsText(file)}
function refreshTeamOptions(sel){$('#userTeam').innerHTML='';universe.teams.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(s=>{let o=document.createElement('option');o.value=s.name;o.textContent=s.name;$('#userTeam').appendChild(o)});$('#userTeam').value=T(sel)?sel:universe.teams[0].name}
function bind(){
 $$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
 $('#simWeek').onclick=simWeek;$('#seasonWeek').onclick=simWeek;$('#simSeason').onclick=simSeason;$('#simConf').onclick=simConferenceChampionships;$('#simPlayoff').onclick=simPlayoff;$('#simDetailedGame').onclick=simulateUserDetailed;$('#autoTarget').onclick=autoTarget;$('#runOffseason').onclick=runOffseason;$('#positionFilter').onchange=renderRoster;$('#userTeam').onchange=render;$('#applyProgramEdit').onclick=applyProgramEdit;
 $('#saveBrowser').onclick=saveBrowser;$('#loadBrowser').onclick=loadBrowser;$('#exportSave').onclick=exportSave;$('#importSave').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{if(e.target.files[0])importSave(e.target.files[0])};
 $('#newUniverse').onclick=()=>{if(confirm('Generate a completely new universe? Unsaved progress will be lost.')){initUniverse();refreshTeamOptions('Chicago Metropolitan');render();setStatus('New universe generated.')}};
}
loadSchools().then(()=>{initUniverse();refreshTeamOptions('Chicago Metropolitan');POS.forEach(p=>{let o=document.createElement('option');o.value=p;o.textContent=p;$('#positionFilter').appendChild(o)});allConfs().forEach(c=>{let o=document.createElement('option');o.value=c;o.textContent=c;$('#editConference').appendChild(o)});bind();render();setStatus('v0.4 ready. Export or Save to preserve a dynasty.');}).catch(e=>{$('#app').innerHTML='<div style="padding:30px">Could not initialize Dynasty Lab. '+e.message+'</div>'});
